// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ScrollTo from '@stimulus-components/scroll-to'
application.register("scroll-to", ScrollTo)

import HideScrollBtnController from "./home/hide_scroll_btn_controller"
application.register("home--hide-scroll-btn", HideScrollBtnController)
