// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Maps__AutocompleteController from "./maps/autocomplete_controller"
application.register("maps--autocomplete", Maps__AutocompleteController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import FormImagePreviewController from "./form/image_preview_controller"
application.register("form--image-preview", FormImagePreviewController)

import FormRegistrationController from "./form/registration_controller"
application.register("form--registration", FormRegistrationController)

import FormEmailValidationController from "./form/email_validation_controller"
application.register("form--email-validation", FormEmailValidationController)

import Dialog from '@stimulus-components/dialog'
application.register('dialog', Dialog)
